version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
    ports:
      - 3000:3000
